import Header from '@/components/Header'
import Head from 'next/head'
import LoginPage from './Login'
import HomePage from './Home'


export default function Home() {





  return (
    <>
      <Head>
        <title>BIG | Saas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage></LoginPage>
    </>
  )
}
